### ISSUE TITLE
Support linux extended file attributes (like in gnu tar)

### ISSUE THREAD

**Issue by noiseless** [alexcrichton/tar-rs#65]
Now extended attributes causes error:

thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: TarError { desc: "failed to unpacked `./PaxHeaders.4811/test`", io: Error { repr: Custom(Custom { kind: Other, error: StringError("unknown file type 0x78") }) } } }) }', src/libcore/result.rs:746

More about extended attributes: http://linux.die.net/man/5/attr
From gnu tar man:

``` bash
$ man tar | cat | egrep -A 1 "\-\-xattrs$"
       --xattrs
              Enable extended attributes support.
```

Environment:

``` bash
$ grep ^NAME /etc/os-release
NAME="Arch Linux"
$ uname -ro
4.5.5 GNU/Linux
$ tar --version
tar (GNU tar) 1.29
$ rustc -V
rustc 1.9.0
```

tar-rs = "0.3"
How to reproduce error:

``` bash
$ cargo new --bin tar_test
$ cd tar_test
$ mkdir test
$ head -c 10 /dev/urandom > test/file
$ setfattr -n user.pax.flags -v "epm" ./test/file
$ tar cf test.tar test --xattrs
$ rm -fr test

$ echo "extern crate tar;
use std::fs::File;
use tar::Archive;

fn main() {
    let file = File::open(\"test.tar\").unwrap();
    let mut a = Archive::new(file);
    a.unpack(\"./\").unwrap();
}" > src/main.rs

$ echo "tar = \"0.3\"" >> Cargo.toml

$ RUST_BACKTRACE=1 cargo run 
     Running `target/debug/tar_test`
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: TarError { desc: "failed to unpacked `./PaxHeaders.4811/test`", io: Error { repr: Custom(Custom { kind: Other, error: StringError("unknown file type 0x78") }) } } }) }', src/libcore/result.rs:746
stack backtrace:
   1:      0x39e99e41b20 - std::sys::backtrace::tracing::imp::write::h4c73fcd3363076f5
   2:      0x39e99e445fb - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::h0422dbb3077e6747
   3:      0x39e99e44283 - std::panicking::default_hook::haac48fa641db8fa2
   4:      0x39e99e3b16f - std::sys_common::unwind::begin_unwind_inner::h39d40f52add53ef7
   5:      0x39e99e3bbd8 - std::sys_common::unwind::begin_unwind_fmt::h64c0ff793199cc1b
   6:      0x39e99e41001 - rust_begin_unwind
   7:      0x39e99e7a66f - core::panicking::panic_fmt::h73bf9d7e8e891a73
   8:      0x39e99e27b67 - core::result::unwrap_failed::h8b8227d746f1a946
                        at src/libcore/macros.rs:29
   9:      0x39e99e28194 - _<std..result..Result<T, E>>::unwrap::hb270ae070ca117b6
                        at src/libcore/result.rs:687
  10:      0x39e99e277d9 - tar_test::main::hc9d9cb77fed05a4d
                        at src/main.rs:10
  11:      0x39e99e43ec4 - std::sys_common::unwind::try::try_fn::h09ba69fd13531e58
  12:      0x39e99e40f8b - __rust_try
  13:      0x39e99e4390b - std::rt::lang_start::h5b0863080165c75e
  14:      0x39e99e2a959 - main
  15:      0x33e3bc79740 - __libc_start_main
  16:      0x39e99e275f8 - _start
  17:                0x0 - <unknown>
error: Process didn't exit successfully: `target/debug/tar_test` (exit code: 101)
```

**Comment by alexcrichton** [comment]
Thanks for the report! Support for this was actually added in 0.4, could you try giving that a spin and seeing if it works for you?

**Comment by noiseless** [comment]
Thanks for the reply!

I updated tar-rs to 0.4.6. Now it's not panicing, but also doesn't keep extended attributes.
You can reproduce this behavior using code from my first message.
```
$ setfattr -n user.pax.flags -v "epm" ./test/file
$ getfattr test/file
# file: test/file
user.pax.flags

$ tar cf test.tar test --xattrs
$ rm -fr test
$ tar xvf test.tar --xattrs
test/
test/file
$ getfattr test/file
# file: test/file
user.pax.flags
$ rm -fr test
$ ./target/debug/tar_test
$ getfattr test/file
$
```
Is there a way to access extended file attributes inside archive or keep
it after extraction?

**Comment by alexcrichton** [comment]
Ah yeah these currently aren't extensively processed beyond a few I think. You should be able to access all of them via the [`Entry::pax_extensions`](http://alexcrichton.com/tar-rs/tar/struct.Entry.html#method.pax_extensions) method, however.

I'd be fine taking a PR to handle more of them though!

**Comment by noiseless** [comment]
I implemented saving attributes when unpacking. I'll send a PR after some code cleanup and possible implementation of creating an archive with xattrs.

**Comment by alexcrichton** [comment]
Nice! If it's hard to do feel free to send a PR and I'll see if I can help out

**Comment by lucab** [comment]
Triage bump, I think this has actually been closed via https://github.com/alexcrichton/tar-rs/pull/66.

**Comment by alexcrichton** [comment]
Thanks for the bump @lucab!
